// components/PersistentLogSidebar.tsx
"use client";
import { useEffect, useState } from "react";
import { ActionLog } from "@/lib/types";

export default function PersistentLogSidebar() {
  const [logs, setLogs] = useState<ActionLog[]>([]);

  useEffect(() => {
    // Listener for real-time logs generated by user clicks or backend
    const handleNewLog = (e: any) => {
      setLogs(prev => [e.detail, ...prev].slice(0, 50));
    };

    window.addEventListener("new-log", handleNewLog);
    return () => window.removeEventListener("new-log", handleNewLog);
  }, []);

  return (
    <div className="h-full bg-[#0d1117]/95 backdrop-blur-xl border-l border-white/10 text-[#58a6ff] font-mono text-[11px] flex flex-col">
      <div className="p-4 border-b border-white/10 bg-black/20 flex justify-between items-center">
        <span className="uppercase tracking-widest font-black text-[10px]">Agent_Telemetry_Feed</span>
        <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
      </div>

      <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scroll">
        {logs.map((log) => (
          <div key={log.log_id} className="border-b border-white/5 pb-3 last:border-0 opacity-90 hover:opacity-100 transition-opacity">
            <div className="flex justify-between text-[9px] text-gray-500 mb-1">
              <span>{log.agent}</span>
              <span>{new Date(log.timestamp).toLocaleTimeString()}</span>
            </div>
            <p className="text-white mb-1"><span className="text-blue-500">❯</span> {log.action}</p>
            <p className="text-gray-500 italic text-[10px] leading-tight">Reasoning: {log.reasoning}</p>
          </div>
        ))}
        {logs.length === 0 && (
          <div className="text-center py-20 text-gray-600 animate-pulse">
            Awaiting System Initialization...
          </div>
        )}
      </div>
    </div>
  );
}